sudo: false

language: python
python:
  - "3.6"
  - "3.8"

addons:
  sonarcloud:
  organization: "MK981"
  token: "8B5XXfoXnSjjtH5cVMYTi9ZSHbfIi5J0r"

install:
  - pip install -r requirements.txt
  - pip install unittest2

script:
  - python lab4.py

after_success:
  - coveralls